# This is a basic workflow to help you get started with Actions

name: Build app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SKA: ${{ secrets.SIGNING_KEY_ALIAS }}
      SKP: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SSF: ${{ secrets.SIGNING_STORE_FILE }}
      SSP: ${{ secrets.SIGNING_STORE_PASSWORD }}
      STORE_NAME : "keystore.jks"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Decode
        run:
          echo $SSF > keystore.txt
          base64 -d keystore.txt > $GITHUB_WORKSPACE/$STORE_NAME
      - name: add perms
        run: chmod -R 777 ./gradlew

      - name: Build apk
        run: ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/$STORE_NAME \
          -Pandroid.injected.signing.store.password=$SSP \
          -Pandroid.injected.signing.key.alias=$SKA \
          -Pandroid.injected.signing.key.password=$SKP

      - name: Build AAB
        run: ./gradlew bundleRelease \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/$STORE_NAME \
          -Pandroid.injected.signing.store.password=$SSP \
          -Pandroid.injected.signing.key.alias=$SKA \
          -Pandroid.injected.signing.key.password=$SKP

      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
